beatoncloud/models.py
from beatoncloud import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(200), nullable=False)
    is_active = db.Column(db.Boolean, default=True)

    def is_active(self):
        # 이 사용자가 활성 상태인지 여부를 반환
        return self.active


class InterestInfo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    classic = db.Column(db.Boolean, default=False)
    jazz = db.Column(db.Boolean, default=False)
    pop = db.Column(db.Boolean, default=False)
    ballade = db.Column(db.Boolean, default=False)
    hiphop = db.Column(db.Boolean, default=False)
    reggae = db.Column(db.Boolean, default=False)
    trot = db.Column(db.Boolean, default=False)
    electronic = db.Column(db.Boolean, default=False)
    rock = db.Column(db.Boolean, default=False)
    rnb = db.Column(db.Boolean, default=False)

beatoncloud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, EmailField, BooleanField, SubmitField
from wtforms.validators import DataRequired, EqualTo, Email


class UserCreateForm(FlaskForm):
    email = EmailField("이메일", validators=[DataRequired(), Email()])
    password1 = PasswordField(
        "비밀번호", validators=[DataRequired(), EqualTo("password2", "비밀번호가 일치하지 않습니다")]
    )
    password2 = PasswordField("비밀번호확인", validators=[DataRequired()])


class UserLoginForm(FlaskForm):
    email = EmailField("이메일", validators=[DataRequired(), Email()])
    password = PasswordField("비밀번호", validators=[DataRequired()])
    remember = BooleanField("로그인 상태 유지")
    submit = SubmitField("로그인")


class RegisterInterestForm(FlaskForm):
    classic = BooleanField("클래식")
    jazz = BooleanField("재즈")
    pop = BooleanField("팝")
    ballade = BooleanField("발라드")
    hiphop = BooleanField("힙합")
    reggae = BooleanField("레게")
    trot = BooleanField("트로트")
    electronic = BooleanField("일렉트로닉")
    rock = BooleanField("락")
    rnb = BooleanField("R&B")

beatoncloud/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

import config

db = SQLAlchemy()
migrate = Migrate()


def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    # ORM
    db.init_app(app)
    migrate.init_app(app, db)

    # 블루프린트
    from .views import main_views, auth_views, search_views

    app.register_blueprint(main_views.bp)
    app.register_blueprint(auth_views.bp)
    app.register_blueprint(search_views.bp)

    # flask-login 적용
    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    from .models import User

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(id)

    return app

beatoncloud/views/auth_views.py
from flask import (
    Blueprint,
    url_for,
    render_template,
    flash,
    request,
    session,
    g,
    current_app,
)
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
from flask_login import login_user
from datetime import timedelta

from beatoncloud import db
from beatoncloud.forms import UserCreateForm, UserLoginForm, RegisterInterestForm
from beatoncloud.models import User, InterestInfo

bp = Blueprint("auth", __name__, url_prefix="/")


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get("user_id")
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route("/login/", methods=("GET", "POST"))
def login():
    form = UserLoginForm()
    if request.method == "POST" and form.validate_on_submit():
        error = None
        user = User.query.filter_by(email=form.email.data).first()
        if not user or not check_password_hash(user.password, form.password.data):
            error = "이메일 또는 비밀번호가 올바르지 않습니다."

        if error is None:
            session.clear()
            session["user_id"] = user.id

            if form.remember.data:
                # 로그인 상태를 유지하는 경우에만 세션을 영구적으로 설정
                session.permanent = True
                current_app.permanent_session_lifetime = timedelta(minutes=1)
            else:
                # 로그인 상태를 유지하지 않는 경우 브라우저 세션 동안만 세션 유지
                session.permanent = False

            login_user(user, remember=form.remember.data)

            return redirect(url_for("main.index"))

        flash(error)

    return render_template("auth/login.html", form=form)


@bp.route("/logout/")
def logout():
    session.clear()
    return redirect(url_for("main.index"))


@bp.route("/signup/", methods=("GET", "POST"))
def signup():
    form = UserCreateForm()
    if request.method == "POST" and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if not user:
            user = User(
                email=form.email.data,
                password=generate_password_hash(form.password1.data),
            )
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("auth.register_interest"))
        else:
            flash("이미 존재하는 사용자입니다.")
    return render_template("auth/signup.html", form=form)


@bp.route("/register_interest/", methods=("GET", "POST"))
def register_interest():
    form = RegisterInterestForm()

    if form.validate_on_submit():
        interest_info = InterestInfo(
            classic=form.classic.data,
            jazz=form.jazz.data,
            pop=form.pop.data,
            ballade=form.ballade.data,
            hiphop=form.hiphop.data,
            reggae=form.reggae.data,
            trot=form.trot.data,
            electronic=form.electronic.data,
            rock=form.rock.data,
        )

        db.session.add(interest_info)
        db.session.commit()
        return redirect(url_for("auth.login"))

    return render_template("select_interest.html", form=form)

beatoncloud/views/main_views.py
"""_summary_

    Returns:
        _type_: _description_
"""
from flask import Blueprint, render_template


bp = Blueprint("main", __name__, url_prefix="/")


@bp.route("/")
def index():
    """_summary_

    Returns:
        _type_: _description_
    """
    return render_template("index.html")

beatoncloud/views/search_views.py
from flask import Blueprint, render_template, request, redirect, session
from spotipy.oauth2 import SpotifyClientCredentials, SpotifyOAuth

import spotipy
import json

CLIENT = json.load(open("beatoncloud\conf.json", "r+"))

client_credentials_manager = SpotifyClientCredentials(
    client_id=CLIENT["id"], client_secret=CLIENT["secret"]
)

bp = Blueprint("search", __name__, url_prefix="/")
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)


@bp.route("/search/", methods=["GET"])
def search_results():
    query = request.args.get("query")
    if query:
        # 사용자의 쿼리로 Spotify API 검색 수행
        data = sp.search(q=query, limit=1, type="artist")
        print(data)
        artists = data.get("artists", {}).get("items", [])
        artist_id = artists[0].get("id")

        albums = sp.artist_albums(artist_id)
        top_tracks = sp.artist_top_tracks(artist_id, country="KR")

        artist_albums = [
            {
                "id": album["id"],
                "name": album["name"],
                "release_date": album["release_date"],
                "images": album.get("images", []),
            }
            for album in albums["items"]
        ]

        artist_info = {
            "albums": artist_albums,
            "top_tracks": [
                {
                    "id": track["id"],
                    "name": track["name"],
                    "preview_url": track.get("preview_url", None),
                }
                for track in top_tracks["tracks"]
            ],
        }

        return render_template(
            "result.html",
            query=query,
            artists=artists,
            artist_albums=artist_albums,
            artist_info=artist_info,
            token=session.get("token", None),
        )
    else:
        return render_template("index.html")

beatoncloud/views/test.py
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pprint

cid = "193aa245183a47b4846423c5bc22d975"
secret = "ce680cd732c64a8ba9e5d3dcf32d3143"
client_credentials_manager = SpotifyClientCredentials(
    client_id=cid, client_secret=secret
)

sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

result = sp.search("아이즈원", limit=1, type="album")
pprint.pprint(result)

import urllib.request

urllib.request.urlretrieve(result["albums"]["items"][0]["images"][0]["url"], "18.jpg")

beatoncloud/templates/base.html
<!doctype html>
<html lang="ko">
  <script src="../static/assets/js/color-modes.js"></script>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BeatOnCloud</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link href="../static/assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      body,
      html {
        height: 100%;
        margin: 0;
      }

      #background-img {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        overflow: hidden;
        filter: brightness(50%);
      }

      #background-img img {
        width: 100%;
        height: 100%;
        object-fit: cover;
      }
    </style>
  </head>
   
  <body>
    {% block content %}
    {% endblock %}

    <script src="../static/assets/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

beatoncloud/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

beatoncloud/templates/index.html
{% extends "base.html" %}
{% block content %}

<link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet">

<div id="background-img">
  <img src="../static/assets/imgs/background/main_background.webp">
</div>

<header class="d-flex align-items-center">
  <div class="logo">
    <img src="../static/assets/imgs/logo/logo.ico" alt="웹서비스 로고">
  </div>
  {% if g.user %}
  <div class="dropdown">
    <button class="btn btn-secondary btn-circle dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
        <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
      </svg>
    </button>    
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="{{ url_for('auth.logout')}}">로그아웃</a></li>
    </ul>
  </div>
  {% else %}
  <div class="btn-group">
    <a href="{{ url_for('auth.login')}}" class="btn btn-secondary" aria-current="page">로그인</a>
    {% endif %}
  </div>
</header>

<form action="{{ url_for('search.search_results') }}" method="GET">   
  <input type="text" name="query" placeholder="검색어를 입력하세요">
</form>

{% endblock %}

beatoncloud/templates/result.html
{% extends "base.html" %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='result.css') }}">

<header class="d-flex justify-content-between align-items-center">
  <div class="logo">
    <a href="{{ url_for('main.index') }}">
      <img src="../static/assets/imgs/logo/logo.ico" alt="웹서비스 로고">
    </a>  
  </div>
  
  <form action="{{ url_for('search.search_results') }}" method="GET">   
    <input type="text" name="query" placeholder="검색어를 입력하세요">
  </form>
  
  <div class="space"></div>

  {% if g.user %}
  <div class="dropdown">
    <button class="btn btn-secondary btn-circle dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
        <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
      </svg>
    </button>    
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <li><a class="dropdown-item" href="{{ url_for('auth.logout')}}">로그아웃</a></li>
    </ul>
  </div>
  {% else %}
  <div class="btn-group">
    <a href="{{ url_for('auth.login')}}" class="btn btn-secondary" aria-current="page">로그인</a>
    {% endif %}
  </div>
</header>

<div class="container text-center">
  <div class="row">
    <div class="col-md-8"> 
      <div class="grid text-center">
        <h2 class="h4 mb-4 fw-normal">검색 결과</h2>

        {% if artists %}
          {% for artist in artists %}
            <div class="card" style="--card-color: #727777;">
              <img src="{{ artist.images[0].url }}" alt="{{ artist.name }}" data-testid="card-image" class="w-25 p-3">
              <div class="info">
                <a class="Nqa6Cw3RkDMV8QnYreTr" title="{{ artist.name }}">
                  <div class="Type__TypeElement-sc-goli3j-0 gIkgYW nk6UgB4GUYNoAcPtAQaG" data-encore-id="type">
                    {% if artist.name_kor %}{{ artist.name_kor }}{% else %}{{ artist.name }}{% endif %}
                  </div>
                </a>
                <div class="Type__TypeElement-sc-goli3j-0 bDHxRN Za_uNH8nTZ0qCuIqbPLZ k2ndSrHzhAsXBcLqRKYx" data-encore-id="type">
                  <span>{% if artist.type == "artist" %}아티스트{% else %}{{ artist.type }}{% endif %}</span>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
        {% else %}
          <p>결과가 없습니다.</p>
        {% endif %}
      </div> <!-- Move this </div> inside the grid text-center div -->
    </div>
    <div class="col-6 col-md-4">
      <div class="grid text-center">
        <h2 class="h4 mb-4 fw-normal">Top Tracks</h2>

        {% if artist_info.top_tracks %}
          {% for track in artist_info.top_tracks[:1] %}
            <div class="card">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                  <h5 class="card-title">{{ track.name }}</h5>
                  {% if track.preview_url %}
                    <audio controls>
                      <source src="{{ track.preview_url }}" type="audio/mpeg">
                      Your browser does not support the audio tag.
                    </audio>
                  {% else %}
                    <p>미리보가 없습니다.</p>
                  {% endif %}
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
        {% else %}
          <p>노래가 없습니다.</p>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-6 col-md-4">.col-6 .col-md-4</div>
    <div class="col-6 col-md-4">.col-6 .col-md-4</div>
    <div class="col-6 col-md-4">.col-6 .col-md-4</div>
</div>



<!--
    <div class="col-md-8">
      <div class="grid text-center">
        <h2 class="h4 mb-4 fw-normal">Top Tracks</h2>

        {% if artist_info.top_tracks %}
          {% for track in artist_info.top_tracks[:1] %}
            <div class="card">
              <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                  <h5 class="card-title">{{ track.name }}</h5>
                  {% if track.preview_url %}
                    <audio controls>
                      <source src="{{ track.preview_url }}" type="audio/mpeg">
                      Your browser does not support the audio tag.
                    </audio>
                  {% else %}
                    <p>미리보가 없습니다.</p>
                  {% endif %}
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
        {% else %}
          <p>노래가 없습니다.</p>
        {% endif %}
      </div>
    </div>


<h2>아티스트</h2>
{% if artists %}
    <div class="row row-cols-8">
    {% for artist in artists[:8] %}
      <div class="card" style="--card-color: #727777;">
        <img src="{{ artist.images[0].url }}" alt="{{ artist.name }}" data-testid="card-image">
        <div class="info">
          <a class="Nqa6Cw3RkDMV8QnYreTr" title="{{ artist.name }}">
            <div class="Type__TypeElement-sc-goli3j-0 gIkgYW nk6UgB4GUYNoAcPtAQaG" data-encore-id="type">
              {% if artist.name_kor %}{{ artist.name_kor }}{% else %}{{ artist.name }}{% endif %}
            </div>
          </a>
          <div class="Type__TypeElement-sc-goli3j-0 bDHxRN Za_uNH8nTZ0qCuIqbPLZ k2ndSrHzhAsXBcLqRKYx" data-encore-id="type">
            <span>{% if artist.type == "artist" %}아티스트{% else %}{{ artist.type }}{% endif %}</span>
          </div>
        </div>
      </div>
    {% endfor %}
{% else %}
  <p>결과가 없습니다.</p>
{% endif %}

<h2>앨범</h2>

  {% if artist_albums %}
      <div class="row row-cols-8">    
          {% for album in artist_albums[:8] %}
              <div class="card">
                  <img src="{{ album.images[0].url }}" alt="{{ album.name }}" class="card-img-top">
                  <div class="card-body">
                      <h5 class="card-title">{{ album.name }}</h5>
                      <p class="card-text">{{ album.release_date }}</p>
                  </div>
              </div>
          {% endfor %}
      </div>
  {% else %}
      <p>앨범이 없습니다.</p>
  {% endif %}


<h2 class="h4 mb-4 fw-normal">Top Tracks</h2>

  {% if artist_info.top_tracks %}
      <div class="row row-cols-8">
          {% for track in artist_info.top_tracks[:8] %}
              <div class="card">
                <div class="card-body">
                      <h5 class="card-title">{{ track.name }}</h5>
                      {% if track.preview_url %}
                          <audio controls>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-play" viewBox="0 0 16 16">
                              <path d="M10.804 8 5 4.633v6.734zm.792-.696a.802.802 0 0 1 0 1.392l-6.363 3.692C4.713 12.69 4 12.345 4 11.692V4.308c0-.653.713-.998 1.233-.696z"/>
                            </svg>
                              <source src="{{ track.preview_url }}" type="audio/mpeg">
                              Your browser does not support the audio tag.
                          </audio>
                      {% else %}
                          <p>미리보가 업습니다.</p>
                      {% endif %}
                  </div>
              </div>
          {% endfor %}
      </div>
  {% else %}
      <p>노래가 없습니다.</p>
  {% endif %}

  <h1>Spotify Web Playback SDK Quick Start</h1>
    <button id="togglePlay">Toggle Play</button>

    <script src="https://sdk.scdn.co/spotify-player.js"></script>
    <script>
        window.onSpotifyWebPlaybackSDKReady = () => {
            const token = 'BQBbxMiOfwgyNx6tg2mPv70Vp2WJ1PZSCMut9eCJhXOhId-4J4dAw8kUL4zLVODkIil8k_fvqRt9RGgmZez-4_LLbBjUZqYxoZZZH_rNSprkBZQj-JmiIV80hLkOHrCvyzranbv782QQuXDPi8dReSBYatiax4z_MvarsL7mBQJbkbMTk--ZSv1tDjsZLAaszhZbjIp7ezDCG-axMF7DhiEI';
            const player = new Spotify.Player({
                name: 'Web Playback SDK Quick Start Player',
                getOAuthToken: cb => { cb(token); },
                volume: 0.5
            });

            // Ready
            player.addListener('ready', ({ device_id }) => {
                console.log('Ready with Device ID', device_id);
            });

            // Not Ready
            player.addListener('not_ready', ({ device_id }) => {
                console.log('Device ID has gone offline', device_id);
            });

            player.addListener('initialization_error', ({ message }) => {
                console.error(message);
            });

            player.addListener('authentication_error', ({ message }) => {
                console.error(message);
            });

            player.addListener('account_error', ({ message }) => {
                console.error(message);
            });

            document.getElementById('togglePlay').onclick = function() {
              player.togglePlay();
            };

            player.connect();
        }
    </script>    
-->
{% endblock %}


<div class="container text-center">
  <!-- Stack the columns on mobile by making one full-width and the other half-width -->
  <div class="row">
    <div class="col-md-8">.col-md-8</div>
    <div class="col-6 col-md-4">.col-6 .col-md-4</div>
  </div>

  <!-- Columns start at 50% wide on mobile and bump up to 33.3% wide on desktop -->
  <div class="row">
    <div class="col-6 col-md-4">.col-6 .col-md-4</div>
    <div class="col-6 col-md-4">.col-6 .col-md-4</div>
    <div class="col-6 col-md-4">.col-6 .col-md-4</div>
  </div>
</div>

beatoncloud/templates/select_interest.html
{% extends "base.html" %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='interest.css') }}">

<div id="background-img">
  <img src="../static/assets/imgs/background/login_background.webp">
</div>

<main class="form-signin w-100 m-auto">
  <form method="post">
    {{ form.csrf_token }}
    {% include "form_errors.html" %}
    <h1 class="h3 mb-3 fw-normal">관심사 선택</h1>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                <div class="col">
                    <div class="card shadow-sm align-items-center">
                        <img src="../static/assets/imgs/card/classic.webp" class="card-img-classic" alt="classic">
                        <span class="position-absolute top-0 start-0"><h2 class="h4 mb-4 fw-normal">클래식</h2></span>
                        <div class="card-body">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="classic" name="classic" onclick='is_checked()'>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm align-items-center">
                        <img src="../static/assets/imgs/card/jazz.webp" class="card-img-classic" alt="jazz">
                        <span class="position-absolute top-0 start-0"><h2 class="h4 mb-4 fw-normal">재즈</h2></span>
                        <div class="card-body">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="jazz" name="jazz" onclick='is_checked()'>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm align-items-center">
                        <img src="../static/assets/imgs/card/pop.webp" class="card-img-classic" alt="pop">
                        <span class="position-absolute top-0 start-0"><h2 class="h4 mb-4 fw-normal">팝</h2></span>
                        <div class="card-body">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="pop" name="pop" onclick='is_checked()'>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm align-items-center">
                        <img src="../static/assets/imgs/card/ballade.webp" class="card-img-classic" alt="ballade">
                        <span class="position-absolute top-0 start-0"><h2 class="h4 mb-4 fw-normal">발라드</h2></span>
                        <div class="card-body">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="ballade" name="ballade" onclick='is_checked()'>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm align-items-center">
                        <img src="../static/assets/imgs/card/hiphop.webp" class="card-img-classic" alt="hiphop">
                        <span class="position-absolute top-0 start-0"><h2 class="h4 mb-4 fw-normal">힙합</h2></span>
                        <div class="card-body">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="hiphop" name="hiphop" onclick='is_checked()'>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm align-items-center">
                        <img src="../static/assets/imgs/card/reggae.webp" class="card-img-classic" alt="reggae">
                        <span class="position-absolute top-0 start-0"><h2 class="h4 mb-4 fw-normal">레게</h2></span>
                        <div class="card-body">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="reggae" name="reggae" onclick='is_checked()'>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm align-items-center">
                        <img src="../static/assets/imgs/card/trot.webp" class="card-img-classic" alt="trot">
                        <span class="position-absolute top-0 start-0"><h2 class="h4 mb-4 fw-normal">트로트</h2></span>
                        <div class="card-body">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="trot" name="trot" onclick='is_checked()'>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm align-items-center">
                        <img src="../static/assets/imgs/card/electronic.webp" class="card-img-classic" alt="electronic">
                        <span class="position-absolute top-0 start-0"><h2 class="h4 mb-4 fw-normal">일렉트로닉</h2></span>
                        <div class="card-body">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="electronic" name="electronic" onclick='is_checked()'>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm align-items-center">
                        <img src="../static/assets/imgs/card/rock.webp" class="card-img-classic" alt="rock">
                        <span class="position-absolute top-0 start-0"><h2 class="h4 mb-4 fw-normal">락</h2></span>
                        <div class="card-body">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="rock" name="rock" onclick='is_checked()'>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm align-items-center">
                        <img src="../static/assets/imgs/card/rnb.webp" class="card-img-classic" alt="rnb">
                        <span class="position-absolute top-0 start-0"><h2 class="h4 mb-4 fw-normal">R&B</h2></span>
                        <div class="card-body">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="rnb" name="rnb" onclick='is_checked()'>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <button class="btn btn-primary w-100 py-2" type="submit">완료</button>
  </form>
</main>

{% endblock %}